---
- name: Create a file impersonating to other user
  hosts: all
  gather_facts: false
  tasks:
    - name: Display message as non-admin
      ansible.builtin.debug: 
        msg: The next task is executed as Administrator

    - ansible.windows.win_whoami:

    - name: Display message as admin
      ansible.builtin.debug:
        msg: The next task is executed as Non-Administrator

    ansible.windows.win_whoami:
    become: true
