[libdefaults]
  default_realm = EXAMPLE01.COM
  dns_lookup_realm = false
  dns_lookup_kdc = false
  
[realms]
  EXAMPLE01.COM = {
    kdc = 192.168.122.132
    admin_server = 192.168.122.132
  }
  
[domain_realm]
  .example01.com = EXAMPLE01.COM
  EXAMPLE01.COM = EXAMPLE01.COM
